name: Build
on: [ push ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew shadowJar

      - name: Calculate SHA-256 hash of the jar
        id: sha256
        run: |
          echo "SHA256=$(shasum -a 256 $(find build/libs -name '*.jar') | awk '{print $1}')" >> $GITHUB_ENV

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "jar archive"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.TOKEN }}"
          body: "$(cat $GITHUB_ENV | grep SHA256)"
          files: |
            build/libs/*.jar
          prerelease: false
